version: '3.9'

services:
  python:
    image: compiler:latest
    build:
      context: .
      dockerfile: .Dockerfile
    platform: linux/amd64
    volumes:
      - ./src:/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - pipenv:/src/app/.venv
      - vscode-server:/root/.vscode-server
    environment:
      - DISPLAY=${HOSTNAME}:0 # for XQuartz

volumes:
  pipenv:
  vscode-server: